#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./env
source "$script_dir/env"

uname_out="$(uname -s)"
case "$uname_out" in
	Linux*)
		linux=true;;
	*)
		linux=false
esac

if $linux && ! [ "${1:-}" == "--skip-musl" ]
then
	if [ -z "${TARGET_FLAG:-}" ]
	then
		TARGET_FLAG="--target=x86_64-unknown-linux-musl"
	else
		>&2 echo "\
ERROR: Trying to set target to MUSL (--skip-musl was not given), \
but TARGET_FLAG is already set!"
		exit 3
	fi
fi

CARGO_FLAGS=()
if [ -n "$TARGET_FLAG" ]
then
	CARGO_FLAGS+=("$TARGET_FLAG")
fi
$CARGO build --verbose --release "${CARGO_FLAGS[@]}"

if [ -f "$BINARY_PATH" ]
then
	strip "$BINARY_PATH"
fi
