#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./env
source "$script_dir/env"

if [ -z "${TARGET_FLAGS_ARRAY:-}" ]
then
	TARGET_FLAGS_ARRAY=()
	TARGET_FLAGS_ARRAY+=("--target=x86_64-unknown-linux-musl")
	if ! which musl-gcc > /dev/null
	then
		>&2 echo "ERROR: Trying to compile with MUSL (system independent binaries), \
			but 'musl-gcc is not installed!'"
		exit 2
	fi
fi
$CARGO build --verbose --release "${TARGET_FLAGS_ARRAY[@]}"

if [ -f "$BINARY_PATH" ]
then
	strip "$BINARY_PATH"
fi
