#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  liblz4-tool \
  musl-tools \
  wget \
  xz-utils

if ! which stoml
then
	mkdir -p target/tools
	wget "https://github.com/freshautomations/stoml/releases/download/v0.7.0/stoml_linux_amd64" \
		-O stoml
	chmod +x target/tools/stoml
fi
