#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

#script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
#source "$script_dir/env"

# We run all tests, even if some are failing.

exit=0

echo
echo
echo "TEST: 'cargo test' - Run unit-tests ..."
cargo test --release --lib || exit=$?

echo
echo
echo "TEST: 'cargo fmt' - Check source code formatting ..."
cargo fmt -- --check || exit=$?

echo
echo
echo "TEST: 'cargo clippy' - Static code linting ..."
cargo clippy --release -- \
  --deny clippy::pedantic \
  || exit=$?

echo
echo
echo "TEST: 'cargo test' - Building documentaiton and running docu code ..."
# This flag will run your code examples as tests.
# For more, see the chapter on documentation tests:
# https://doc.rust-lang.org/rustdoc/documentation-tests.html
cargo test --release --doc || exit=$?

echo
echo
echo "TEST: 'cargo clippy' - Licensing meta-data check ..."
if which reuse > /dev/null
then
  reuse lint || exit=$?
else
  echo "WARNING: REUSE tool not found; skipping licensing meta-data check."
fi

exit $exit
